### ISSUE TITLE
Unhardcode a bunch of type things

### ISSUE THREAD

**Issue by MrChuse** [freegish/freegish#26]
I've started working on unhardcoding various object types in the codebase. These are things such as level object types, gameobject types, rope types and other things. If my pull request #25 with readability changes (or a separate one without multiplayer campaign) will be approved, some of the work on this problem will be merged into the public repository.

However, there are a lot more objects and types to decipher and I hope for this issue to be a to-do list for all the renaming in the codebase.

- [ ] level object types (things you can set in the editor and lvl files). Done in #25, some help is needed with boxes
- [ ] gameobject types (objects that get created based on the level objects). Done in #25
- [ ] rope types. Done in #25
- [ ] light types. Done in #25 
- [ ] more clear what idata members are for. Partially done in #25
- [ ] bond types
- [ ] physicstemp.bond types
- [ ] particle types
- [ ] menuitem types
- [ ] beast types

I'm sure there are more things to unhardcode in the code (I didn't even touch the rendering), so feel free to suggest entries and work on this list
